//POST ACIONS
export const GET_POSTS = "GET_POSTS";
export const GET_POST_LIKES = "GET_POST_LIKES";
export const ADD_POST = "ADD_POST";
export const DELETE_POST = "DELETE_POST";
export const POSTS_LOADING = "POSTS_LOADING";
//AUTH ACTIONS
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCES";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
//ERROR ACTIONS
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
//TODO: SOCKET ACTIONS
export const SOCKET_CONNECT = "SOCKET_CONNECT";
export const SOCKET_CONNECTING = "SOCKET_CONNECTING";
export const SOCKET_CONNECTED = "SOCKET_CONNECTED";
export const SOCKET_DISCONNECT = "SOCKET_DISCONNECT";
export const SOCKET_DISCONNECTED = "SOCKET_DISCONNECTED";
export const SOCKET_ADDED_POST = "SOCKET_ADDED_POST";
export const SOCKET_RECEIVED_NEW_POST_INFO = "SOCKET_RECEIVED_NEW_POST_INFO";

export const MESSAGES_LOADING = "MESSAGES_LOADING";
export const FETCH_PAST_MESSAGES = "FETCH_PAST_MESSAGES";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const MESSAGE_RECEIVED = "MESSAGE_RECEIVED";
